### ISSUE TITLE
Lab single cell: it seems compute power is not enough

### ISSUE THREAD

**Issue by rasools** [NBISweden/workshop_omics_integration#134]
Lab single cell: it seems compute power is not enough.

**Comment by rasools** [comment]
Hi @jenfransson, since you have more experience on this, can you have a check on single cell lab and see what we need to do to make it fully working? Thanks!
https://oisb-h24-lab-single-cell.serve.scilifelab.se/

**Comment by jenfransson** [comment]
I'll check!

**Comment by jenfransson** [comment]
Before getting to any computation, I'm already having a problem finding the file scatacseq_activity_matrix.txt. It's not in the Docker file among the files to be downloaded. @rasools Were you able to run it on Serve? Do you or @LeandroRitter know where to find this file?

**Comment by rasools** [comment]
Umm, I recently updated docker files structure, maybe I made some unwanted changes...
I'll check and write back.
